create table students(regd_no int,name varchar(50),branch varchar(50));
insert into students values(0001,"Ram","CSE");
insert into students values(0002,"Hari","MECH");
insert into students values(0003,"pradeep","EEE");
insert into students values(0004,"deepak","ETC");
select regd_no from students where name ="pradeep";
select name,branch from students;
select count(regd_no) from students;
alter table students
add column address varchar(50);
desc students;
create table employee(empno int unsigned,ename varchar(50),job varchar(50),hire_date date,
mgr int,sal dec,comm int,dept_no int);


desc employee;
truncate employee;
insert into employee values(7369,"smith","clerk",str_to_date('17-dec-80','%d-%M-%Y'),7902,800,null,20);
insert into employee values(7499,"allen","salesman",str_to_date('20-feb-81','%d-%M-%Y'),7698,1600,300,30);
insert into employee values(7521,"ward","salesman",str_to_date('22-feb-81','%d-%M-%Y'),7698,1250,500,30);
insert into employee values(7566,"jones","manager",str_to_date('02-apr-81','%d-%M-%Y'),7839,2975,null,20);
insert into employee values(7564,"martin","salesman",str_to_date('28-sep-81','%d-%M-%Y'),7698,1250,1400,30);
insert into employee values(7698,"blake","manager",str_to_date('01-may-81','%d-%M-%Y'),7839,2850,null,30);
insert into employee values(7782,"clark","manager",str_to_date('09-jun-81','%d-%M-%Y'),7839,2450,null,10);
insert into employee values(7788,"scott","analyst",str_to_date('19-apr-87','%d-%M-%Y'),7566,3000,null,20);
insert into employee values(7839,"king","president",str_to_date('17-nov-81','%d-%M-%Y'),null,5000,null,10);
insert into employee values(7844,"turner","salesman",str_to_date('08-sep-81','%d-%M-%Y'),7698,1500,0,30);
insert into employee values(7876,"adams","clerk",str_to_date('23-may-87','%d-%M-%Y'),7788,1100,null,20);
insert into employee values(7900,"james","clerk",str_to_date('03-dec-81','%d-%M-%Y'),7698,950,null,30);
insert into employee values(7902,"ford","analyst",str_to_date('03-dec-81','%d-%M-%Y'),7566,3000,null,20);
insert into employee values(7934,"miller","clerk",str_to_date('23-jan-82','%d-%M-%Y'),7782,1300,null,10);

desc employee;
select* from employee where dept_no=30;
select empno,ename,job from employee where job='clerk';
select dept_no,ename from employee where (dept_no)>20;
select* from employee where (comm)>(sal);
select* from employee where (comm)>(sal*(60/100));
select ename,job,sal  from employee where (dept_no)=20 && (sal)>2000; 
select* from employee where (dept_no=30) && (sal) >=1500 && job='salesman';
select* from employee where job='manager' || job='president';
select ename,job,dept_no from employee where job='manager' && dept_no!=30;
select* from employee where job=('manager') || job=('clerk') having dept_no=10;
select* from employee where  (job='manager' or (job=('clerk') and dept_no=10) ) ;
select* from employee where ((job=('manager13') and dept_no=10) or  (job=('clerk') and dept_no=20));
select ename from employee where not((job=('manager') or job=('clerk'))) group by ename having (dept_no)=20;  
select ename from employee where sal between 1200 and 1400;
select* from employee where job in('clerk','analyst','salesman');
select* from employee where not job in('clerk','analyst','salesman');
select* from employee where comm is null;
select job from employee where comm is not null;
select* from employee where comm<=100 or comm is null;
select ename ,sal+ (nvl(comm,(comm*sal),(+250))) net_earning from employee;
select* from employee where sal>2000;
select* from employee where ename like 'm%' or ename like '%m';
select* from employee where ename like '%m%';
select* from employee where length(ename)<=15 and ename like '__r%';
select* from employee where  monthname(hire_date)='february';
select* from employee where eomonth(hire_date);
select job from employee where job='manager' or year(hire_date)='2013';
select concat(concat(concat(ename),'  ', job)) from employee;
select lpad(ename,15,' ') from employee;
select trim('a' from ename) from employee;
select trim('r' from ename) from employee;
select concat(substr(ename,1,3),substr(ename,-3)) from employee;
select ename from employee where ename like ('%ar%');
select replace(ename,'a','A') from employee;
select sal,ceil(sal/1000)*1000 from employee;
select* from employee order by ename ;
select ename,hire_date from employee order by hire_date;
select ename,job,sal from employee order by job asc,  sal asc;
select ename,job,sal from employee order by job desc, sal asc;
select ename,job,sal from employee where comm is null or comm = 0 order by job;
select*from employee;
